name: Run Betting Models

on:
  workflow_dispatch:
    inputs:
      tomorrow:
        description: Day to run models (today/tomorrow)
        required: true
        type: string
        default: today

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-models:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run models
        run: |
          python run_models.py ${{ github.event.inputs.tomorrow }} -n